### ISSUE TITLE
Investigate inheritEnv in VS Code

### ISSUE THREAD

**Issue by llttlltt** [Elliott-Liu/dotfiles#5]
[Why are there duplicate paths in the terminal's $PATH environment variable and/or why are they reversed?](https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed)

> There are two direct fixes for this. You can set "terminal.integrated.inheritEnv": false

We've seen two mentions of removing some environment variables (also in the comment below).

> ...which will strip most environment variables from the terminal's environment, except for some important ones (like HOME, SHELL, TMPDIR, etc.).

**Comment by llttlltt** [comment]
Keeping an eye on [eieioxyz](https://github.com/eieioxyz/dotfiles_macos/issues/5)'s issue for more info.

**Comment by Elliott-Liu** [comment]
It seems this is a non-issue as of July 2020 with the introduction of [Settings Sync](https://code.visualstudio.com/updates/v1_48#_settings-sync) in VS Code.

The inheritEnv should remain persistent after login and sync of settings.

**Comment by llttlltt** [comment]
It seems this is a non-issue as of July 2020 with the introduction of [Settings Sync](https://code.visualstudio.com/updates/v1_48#_settings-sync) in VS Code.

The inheritEnv should remain persistent after login and sync of settings.
